name: rootflows
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - root=6.30.2
  - tensorflow=2.14.0
  - tensorflow-probability=0.22.1
  - matplotlib=3.8.2
  - numpy=1.26.3
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - jupyter=1.0.0
  - pandas=2.1.4
  - pyspark=3.5.0