[modes]
train = true
evaluate = true
plotTraining = true

[rootIn]
root_path = "./root/10x10box_10k_jun2023/"
thresh = 150

[generating]
ngen = 500
gen_labels_unique = [2464.0, 5.125]

[outputs]
loss_plot_path = "./output/fullscript/plots/loss_plot.png"
gen_plot_path = "./output/fullscript/plots/generated_plot.png"
train_plot_path = "./output/fullscript/plots/training_plot.png"
root_out_path = "./output/fullscript/root/"
savePlot = true

[network]

[network.compile]
nmade = 10
ninputs = 2
ncinputs = 2
hidden_layers = 1
hidden_units = 128
lr_tuple = [1e-3, 1e-4, 100.0]

[network.train]
starting_epoch = 0
end_epoch = 200
batch_size = 1024
flow_path = "./model/fullscript/"

[callbacks]
log_freq = 10
save_freq = 50